apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.solution_name}}-deployment
  labels:
    app: {{cookiecutter.app_image_name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{cookiecutter.app_image_name}}
  template:
    metadata:
      labels:
        app: {{cookiecutter.app_image_name}}
    spec: 
      containers:
      - name: {{cookiecutter.app_image_name}}
        image: ghcr.io/constellationbrands/{{cookiecutter.app_image_name}}:{{ cookiecutter.app_image_version }}
        ports:
        - containerPort: 8080
