---
apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.solution_name }}-service
spec:
 selector:
   app: {{ cookiecutter.app_image_name }}
 type: ClusterIP  
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
